apiVersion: v1
kind: Service
metadata:
  name: mongodb-fts-api
  namespace: mongodb-fts
  labels:
    app: mongodb-fts-api
spec:
  type: LoadBalancer
  selector:
    app: mongodb-fts-api
  ports:
  - name: http
    port: 80
    targetPort: 5010
    protocol: TCP
